apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: e5-mistral-cache
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.cache.accessMode }}
  resources:
    requests:
      storage: {{ .Values.cache.size }}
  storageClassName: {{ .Values.cache.storageClassName }}
