{{- if .Values.runPipelines.run }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: run-pipelines
  namespace: {{ .Values.namespace }}
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: pipeline-upload-job
      containers:
        - name: run-pipelines
          image: {{ .Values.pipelineTools.image.registry }}/{{ .Values.pipelineTools.image.name }}:{{ .Values.pipelineTools.image.tag }}
          command:
            - sh
            - -c
            - workflows/examples/code_understanding/scripts/run_pipelines.sh {{ .Values.runPipelines.args }}
          workingDir: /opt/app-root/src
          env:
            - name: KFP_HOST
              value: "https://ds-pipeline-dspa.{{ .Values.namespace }}.svc.cluster.local:8443"
            - name: KFP_NAMESPACE
              value: "{{ .Values.namespace }}"
            - name: KFP_DATA_GENERATION_OUTPUT_PATH
              value: "{{ .Values.runPipelines.targetPath }}"
            - name: KFP_DATA_INDEXING_OUTPUT_PATH
              value: "{{ .Values.runPipelines.graphragSourcePath }}"
          envFrom:
            - secretRef:
                name: code-understanding-env
                optional: true
{{- end }}
