---
apiVersion: batch/v1
kind: Job
metadata:
  name: upload-assets
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: pipeline-upload-job
      containers:
        - name: upload-assets
          image: {{ .Values.pipelineTools.image.registry }}/{{ .Values.pipelineTools.image.name }}:{{ .Values.pipelineTools.image.tag }}
          command:
            - sh
            - -c
            - |
              python - <<'PYEOF'
              import sys, os, mlflow
              sys.path.insert(0, '/opt/app-root/src/workflows/examples/code_understanding')
              from loaders.mlflow_asset_loader import MlFlowAssetLoader

              mlflow.set_tracking_uri(os.getenv("MLFLOW_TRACKING_URI", "https://mlflow.redhat-ods-applications.svc:8443"))

              MlFlowAssetLoader().upload_all_assets("workflows/examples/code_understanding/assets")
              PYEOF
          workingDir: /opt/app-root/src
          env:
            - name: MLFLOW_TRACKING_INSECURE_TLS
              value: "true"
            - name: MLFLOW_WORKSPACE
              value: "{{ .Values.namespace }}"
          envFrom:
            - secretRef:
                name: code-understanding-env
