worker_processes auto;
error_log /dev/stderr notice;
pid /tmp/nginx.pid;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log /dev/stdout;
  sendfile on;
  keepalive_timeout 65;

  server {
    listen 9443 ssl;
    server_name _;
    root /usr/share/nginx/html;

    ssl_certificate /var/serving-cert/tls.crt;
    ssl_certificate_key /var/serving-cert/tls.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
      try_files $uri $uri/ /index.html;
    }
  }
}
