namespace: demo
requester: ""
kfpHost: ""
clusterDomain: ""
deployNotebooks: false

repoUrl: ""
repoRef: main

version: latest

minio:
  rootUser: ""
  rootPassword: ""
  bucket: demo
  region: us-east-1

dataGeneration:
  image:
    registry: ""
    name: ""
    title: "Agent Mesh - Data Generation"
    version: latest
    digestRef: ""
  notebook:
    name: data-generation

graphrag:
  image:
    registry: ""
    name: ""
    title: "Agent Mesh - GraphRAG Indexing"
    version: latest
    digestRef: ""
  notebook:
    name: graphrag-indexing

analysis:
  image:
    registry: ""
    name: ""
    title: "Agent Mesh - Analysis"
    version: latest
  notebook:
    name: graphrag-analysis

adhocQuery:
  run: false
  graphragDir: "graph_rag_app/source"
  useGlobal: "1"
  retryCount: "3"
  jobId: ""
  gitRepo: ""
  gitBranch: "main"

runPipelines:
  run: false
  args: "--single"
  targetPath: "target"
  graphragSourcePath: "graph_rag_app/source"
